version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: puml-parallel
    main: ./main.go
    binary: puml-parallel
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: puml-parse
    main: ./tools/parse/main.go
    binary: puml-parse
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: puml-events
    main: ./tools/events/main.go
    binary: puml-events
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: binary
    name_template: >-
      {{ .Binary }}-
      {{- if eq .Os "Darwin" }}darwin-
      {{- else if eq .Os "Linux" }}linux-
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}
    # https://goreleaser.com/errors/multiple-binaries-archive/
    allow_different_binary_count: true

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Kuniwak
    name: puml-parallel
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## PlantUML Parallel Composition {{ .Tag }}

    This release contains the following tools:
    - `puml-parallel`: Main tool for interface parallel of PlantUML state diagrams
    - `puml-parse`: Parser tool for analyzing PlantUML files
    - `puml-events`: Events extraction tool for listing events from PlantUML files

    Download the appropriate archive for your platform and extract the binaries.

  footer: |
    ## Checksums

    All binaries are available with checksums for verification.
    
    **Full Changelog**: https://github.com/Kuniwak/puml-parallel/compare/{{ .PreviousTag }}...{{ .Tag }}
